services:
  db:
    image: postgres:15
    container_name: attendance_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: attendance
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d attendance"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  pgdata:
