name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      NPM_CONFIG_PRODUCTION: "false"
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            server/package-lock.json
            web/package-lock.json

      - name: Force dev installs
        run: |
          echo "production=false" > .npmrc
          if [ -f server/.npmrc ]; then sed -i 's/^production=.*/production=false/' server/.npmrc || true; fi
          if [ -f web/.npmrc ]; then sed -i 's/^production=.*/production=false/' web/.npmrc || true; fi

      - name: Install dependencies (root + workspaces)
        run: npm ci --include=dev --include-workspace-root --workspaces

      - name: Verify ESLint deps
        run: |
          node -e "console.log('globals version:', require('globals/package.json').version)"
          npx eslint -v

      - name: Typecheck (server)
        run: npm run -w server typecheck --if-present

      - name: Typecheck (web)
        run: npm run -w web typecheck --if-present

      - name: Lint (root)
        run: npm run lint --if-present

      - name: Build server
        run: npm run -w server build

      - name: Build web
        run: npm run -w web build

      - name: Upload server build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist
          if-no-files-found: warn

      - name: Upload web build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
          if-no-files-found: warn
