- uses: actions/setup-node@v4
  with:
    node-version: 20
    cache: npm

- name: Install root deps
  run: npm ci

# NEW: ensure server workspace deps (incl. dev) are present for the build
- name: Install server deps
  run: npm ci -w server --include=dev

- name: Build server
  run: npm run -w server build

# Already doing this for web; keep it
- name: Install web devDependencies
  run: npm ci -w web --include=dev

- name: Build web
  run: npm run -w web build
