name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # Force dev installs everywhere (beats any .npmrc or env that sets production)
    env:
      NPM_CONFIG_PRODUCTION: "false"
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            server/package-lock.json
            web/package-lock.json

      # Belt + suspenders: ensure no workspace-level .npmrc flips production=true
      - name: Neutralize .npmrc (root + workspaces)
        run: |
          echo "production=false" > .npmrc
          if [ -f server/.npmrc ]; then sed -i 's/^production=.*$/production=false/' server/.npmrc || true; fi
          if [ -f web/.npmrc ]; then sed -i 's/^production=.*$/production=false/' web/.npmrc || true; fi
          echo "omit=" >> .npmrc   # clear omit flags if any

      - name: Show npm config (debug)
        run: npm config list -l

      # Install ALL deps (including dev) across workspaces
      - name: Install dependencies (all workspaces)
        run: npm ci --workspaces --include=dev

      # Verify key dev deps are present
      - name: Verify ESLint deps
        run: |
          node -e "console.log('globals version:', require('globals/package.json').version)"
          npx eslint -v

      # Typecheck
      - name: Typecheck (server)
        run: npm run -w server typecheck --if-present
      - name: Typecheck (web)
        run: npm run -w web typecheck --if-present

      # Lint from repo root (uses root eslint.config.mjs)
      - name: Lint (root)
        run: npm run lint --if-present

      # Build
      - name: Build server
        run: npm run -w server build
      - name: Build web
        run: npm run -w web build

      # Artifacts
      - name: Upload server build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist
          if-no-files-found: warn

      - name: Upload web build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
          if-no-files-found: warn
